
import { Movie, RecommendationHistory } from './types';

export const MOCK_MOVIES: Record<string, Movie[]> = {
  happy: [
    {
      id: '1',
      title: 'La La Land',
      year: 2016,
      poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=2059&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Comedy', 'Drama', 'Musical'],
      plot: 'While pursuing their dreams in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
      rating: 8.0,
    },
    {
      id: '2',
      title: 'Amélie',
      year: 2001,
      poster: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=2025&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Comedy', 'Romance'],
      plot: 'Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.',
      rating: 8.3,
    },
    {
      id: '3',
      title: 'Sing Street',
      year: 2016,
      poster: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?q=80&w=2056&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Comedy', 'Drama', 'Music'],
      plot: 'A boy growing up in Dublin during the 1980s escapes his strained family life by starting a band to impress the mysterious girl he likes.',
      rating: 7.9,
    },
  ],
  sad: [
    {
      id: '4',
      title: 'Eternal Sunshine of the Spotless Mind',
      year: 2004,
      poster: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Drama', 'Romance', 'Sci-Fi'],
      plot: 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.',
      rating: 8.3,
    },
    {
      id: '5',
      title: 'The Shawshank Redemption',
      year: 1994,
      poster: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Drama'],
      plot: 'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.',
      rating: 9.3,
    },
    {
      id: '6',
      title: 'The Pursuit of Happyness',
      year: 2006,
      poster: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?q=80&w=2074&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Biography', 'Drama'],
      plot: 'A struggling salesman takes custody of his son as he\'s poised to begin a life-changing professional endeavor.',
      rating: 8.0,
    },
  ],
  angry: [
    {
      id: '7',
      title: 'Fight Club',
      year: 1999,
      poster: 'https://images.unsplash.com/photo-1508614999368-9260051292e5?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Drama'],
      plot: 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',
      rating: 8.8,
    },
    {
      id: '8',
      title: 'Taxi Driver',
      year: 1976,
      poster: 'https://images.unsplash.com/photo-1465101162946-4377e57745c3?q=80&w=2078&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Crime', 'Drama'],
      plot: 'A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action.',
      rating: 8.2,
    },
    {
      id: '9',
      title: 'Whiplash',
      year: 2014,
      poster: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Drama', 'Music'],
      plot: 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
      rating: 8.5,
    },
  ],
  fearful: [
    {
      id: '10',
      title: 'The Silence of the Lambs',
      year: 1991,
      poster: 'https://images.unsplash.com/photo-1517999144091-3d9dca6d1e43?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Crime', 'Drama', 'Thriller'],
      plot: 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.',
      rating: 8.6,
    },
    {
      id: '11',
      title: 'Get Out',
      year: 2017,
      poster: 'https://images.unsplash.com/photo-1593642532842-98d0fd5ebc1a?q=80&w=2000&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Horror', 'Mystery', 'Thriller'],
      plot: 'A young African-American visits his white girlfriend\'s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.',
      rating: 7.7,
    },
    {
      id: '12',
      title: 'The Thing',
      year: 1982,
      poster: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Horror', 'Mystery', 'Sci-Fi'],
      plot: 'A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.',
      rating: 8.1,
    },
  ],
  surprised: [
    {
      id: '13',
      title: 'The Sixth Sense',
      year: 1999,
      poster: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=2025&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Drama', 'Mystery', 'Thriller'],
      plot: 'A boy who communicates with spirits seeks the help of a disheartened child psychologist.',
      rating: 8.1,
    },
    {
      id: '14',
      title: 'The Prestige',
      year: 2006,
      poster: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Drama', 'Mystery', 'Sci-Fi'],
      plot: 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
      rating: 8.5,
    },
    {
      id: '15',
      title: 'Inception',
      year: 2010,
      poster: 'https://images.unsplash.com/photo-1496715976403-7e36dc43f17b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Action', 'Adventure', 'Sci-Fi'],
      plot: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
      rating: 8.8,
    },
  ],
  disgusted: [
    {
      id: '16',
      title: 'Trainspotting',
      year: 1996,
      poster: 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?q=80&w=2074&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Drama'],
      plot: 'Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out, despite the allure of the drugs and influence of friends.',
      rating: 8.1,
    },
    {
      id: '17',
      title: 'Requiem for a Dream',
      year: 2000,
      poster: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=2025&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Drama'],
      plot: 'The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.',
      rating: 8.3,
    },
    {
      id: '18',
      title: 'District 9',
      year: 2009,
      poster: 'https://images.unsplash.com/photo-1560109947-543149eceb16?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Action', 'Sci-Fi', 'Thriller'],
      plot: 'Violence ensues after an extraterrestrial race forced to live in slum-like conditions on Earth finds a kindred spirit in a government agent exposed to their biotechnology.',
      rating: 7.9,
    },
  ],
  neutral: [
    {
      id: '19',
      title: 'The Grand Budapest Hotel',
      year: 2014,
      poster: 'https://images.unsplash.com/photo-1527489377706-5bf97e608852?q=80&w=2059&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Adventure', 'Comedy', 'Crime'],
      plot: 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel\'s glorious years under an exceptional concierge.',
      rating: 8.1,
    },
    {
      id: '20',
      title: 'Lost in Translation',
      year: 2003,
      poster: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=2144&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Comedy', 'Drama'],
      plot: 'A faded movie star and a neglected young woman form an unlikely bond after crossing paths in Tokyo.',
      rating: 7.7,
    },
    {
      id: '21',
      title: 'Her',
      year: 2013,
      poster: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Drama', 'Romance', 'Sci-Fi'],
      plot: 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.',
      rating: 8.0,
    },
  ],
  relaxed: [
    {
      id: '22',
      title: 'Before Sunrise',
      year: 1995,
      poster: 'https://images.unsplash.com/photo-1470115636492-6d2b56f9146d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Drama', 'Romance'],
      plot: 'A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna. Unfortunately, both know that this will probably be their only night together.',
      rating: 8.1,
    },
    {
      id: '23',
      title: 'The Secret Life of Walter Mitty',
      year: 2013,
      poster: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Comedy', 'Drama', 'Fantasy'],
      plot: 'When his job along with that of his co-worker are threatened, Walter takes action in the real world embarking on a global journey that turns into an adventure more extraordinary than anything he could have ever imagined.',
      rating: 7.3,
    },
    {
      id: '24',
      title: 'Spirited Away',
      year: 2001,
      poster: 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
      genres: ['Animation', 'Adventure', 'Family'],
      plot: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
      rating: 8.6,
    },
  ],
};

export const MOCK_HISTORY: RecommendationHistory[] = [
  {
    id: '1',
    timestamp: '2023-05-15T14:30:00Z',
    emotion: 'happy',
    movies: MOCK_MOVIES.happy,
  },
  {
    id: '2',
    timestamp: '2023-05-10T20:15:00Z',
    emotion: 'sad',
    movies: MOCK_MOVIES.sad,
  },
  {
    id: '3',
    timestamp: '2023-05-05T12:45:00Z',
    emotion: 'relaxed',
    movies: MOCK_MOVIES.relaxed,
  },
];
